### ISSUE TITLE
Doesn't work with workspaces in yarn

### ISSUE THREAD

**Issue by ghost** [hermanbanken/nsp-preprocessor-yarn#1]
The project I'm currently uses [Workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) for organizing parts of the code into separate (unpublished, private) packages. 

Using this preprocessor doesn't work with this setup. The yarn.lock is in the main folder but all individual package.jsons are in the package folders.

**Comment by hermanbanken** [comment]
Feel free to issue a PR. Should be straight forward. I dont have the time until februari.

**Comment by mririgoyen** [comment]
+1 Would love to see support for workspaces.
