### ISSUE TITLE
Unable to load yarn.lock for project: foo

### ISSUE THREAD

**Issue by dbsanfte** [hermanbanken/nsp-preprocessor-yarn#3]
`sh-4.4$ nsp check --preprocessor yarn`
`(+) Unable to load yarn.lock for project: foo`

https://gist.github.com/dbsanfte/e634e419155db5be732d94a599eadc53

Any ideas why it doesn't like my file?

**Comment by dbsanfte** [comment]
Found the nested error after some hacking:

`sh-4.4$ nsp check --preprocessor yarn`
`(+) yarn.lock is outdated: it does not contain the package ag-grid@17.0.0`

Should really bubble this up to the user instead of swallowing it in index.js.

**Comment by hermanbanken** [comment]
Good one! Will see what I can do.

**Comment by hermanbanken** [comment]
Will release after I have taken a look at #1.
